version: '3'
services:
  node:
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    image: node:10-alpine
    environment:
      - TZ=Europe/Madrid
    volumes:
      - .:/usr/src/app
      - node_modules_cache:/usr/src/app/node_modules
    ports:
      - "8001:8000"
    command: ["yarn", "start"]

volumes:
  node_modules_cache:
